### ISSUE TITLE
*min.js not allowed as exclude

### ISSUE THREAD

**Issue by paul-hammant** [celsomiranda/hexo-beautify#4]
```
$ hexo generate 
FATAL unidentified alias ".min.css" at line 97, column 16:
        - *.min.css
                   ^
Error
    at generateError (/scm/devops/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/scm/devops/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readAlias (/scm/devops/node_modules/js-yaml/lib/js-yaml/loader.js:1248:5)
    at composeNode (/scm/devops/node_modules/js-yaml/lib/js-yaml/loader.js:1340:20)
    at readBlockMapping (/scm/devops/node_modules/js-yaml/lib/js-yaml/loader.js:1008:16)
    at composeNode (/scm/devops/node_modules/js-yaml/lib/js-yaml/loader.js:1331:12)
    at readBlockSequence (/scm/devops/node_modules/js-yaml/lib/js-yaml/loader.js:927:5)
    at composeNode (/scm/devops/node_modules/js-yaml/lib/js-yaml/loader.js:1330:12)
    at readBlockMapping (/scm/devops/node_modules/js-yaml/lib/js-yaml/loader.js:1061:11)
    at composeNode (/scm/devops/node_modules/js-yaml/lib/js-yaml/loader.js:1331:12)
    at readBlockMapping (/scm/devops/node_modules/js-yaml/lib/js-yaml/loader.js:1061:11)
    at composeNode (/scm/devops/node_modules/js-yaml/lib/js-yaml/loader.js:1331:12)
    at readDocument (/scm/devops/node_modules/js-yaml/lib/js-yaml/loader.js:1493:3)
    at loadDocuments (/scm/devops/node_modules/js-yaml/lib/js-yaml/loader.js:1549:5)
    at Object.load (/scm/devops/node_modules/js-yaml/lib/js-yaml/loader.js:1566:19)
    at Hexo.yamlHelper (/scm/devops/node_modules/hexo/lib/plugins/renderer/yaml.js:7:15)
    at Hexo.tryCatcher (/scm/devops/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/scm/devops/node_modules/bluebird/js/release/method.js:15:34)
    at /scm/devops/node_modules/hexo/lib/hexo/render.js:61:21
    at tryCatcher (/scm/devops/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/scm/devops/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/scm/devops/node_modules/bluebird/js/release/promise.js:569:18)
```

Line 97 is, the last line of the following from the documentation from the NPM page for hexo-beautify:

```
# Hexo Beautify
beautify:
  types:
    - html
    - css
    - js
  exclude:
    - *.min.css
```

**Comment by GQH123** [comment]
the same problem

**Comment by tatwd** [comment]
Add `''` here:
``` yml
exclude:
    - '*.min.css'
    - '*.min.js'
```
